#!/usr/bin/env bash
set -euo pipefail

# Optimize a Puppy Linux root filesystem for faster, more reliable boot on mixed laptop hardware.
# Safe defaults; pass --aggressive to disable additional non-essential services.

ROOTFS="/"
AGGRESSIVE=0
DRY_RUN=0

usage() {
  cat <<USAGE
Usage: $0 [--rootfs PATH] [--aggressive] [--dry-run]

Options:
  --rootfs PATH   Path to Puppy Linux root filesystem (default: /)
  --aggressive    Disable extra optional services (CUPS, Samba, BT, Avahi) when present
  --dry-run       Print actions without changing files
USAGE
}

log() {
  echo "[optimize] $*"
}

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRY-RUN: $*"
  else
    eval "$@"
  fi
}

backup_file() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  local backup="${file}.bak.laptoptester"
  if [[ ! -f "$backup" ]]; then
    run "cp -a '$file' '$backup'"
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --rootfs)
      ROOTFS="$2"
      shift 2
      ;;
    --aggressive)
      AGGRESSIVE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! -d "$ROOTFS" ]]; then
  echo "Rootfs path does not exist: $ROOTFS" >&2
  exit 1
fi

ROOTFS="$(cd "$ROOTFS" && pwd)"
log "Optimizing Puppy rootfs at: $ROOTFS"

# 1) Remove stale NIC persistence entries that can increase boot work on changing hardware.
PERSISTENT_NET_RULES="$ROOTFS/etc/udev/rules.d/70-persistent-net.rules"
if [[ -f "$PERSISTENT_NET_RULES" ]]; then
  backup_file "$PERSISTENT_NET_RULES"
  run "rm -f '$PERSISTENT_NET_RULES'"
  log "Removed stale udev persistent-net rules"
fi

# 2) Ensure tester startup is non-blocking and starts WiFi manager in background.
STARTUP_SCRIPT="$ROOTFS/root/Startup/00-laptoptester-startup"
run "mkdir -p '$ROOTFS/root/Startup'"
if [[ -f "$STARTUP_SCRIPT" ]]; then
  backup_file "$STARTUP_SCRIPT"
fi

read -r -d '' STARTUP_CONTENT <<'SCRIPT' || true
#!/bin/sh
# Auto-generated by laptoptester optimization script.
# Keep startup non-blocking so desktop appears quickly.

BASE="/mnt/home/laptoptester"
if [ ! -d "$BASE" ]; then
  BASE="/root/laptoptester"
fi

if [ -f "$BASE/wifi_manager.py" ]; then
  python3 "$BASE/wifi_manager.py" >/tmp/laptoptester_wifi.log 2>&1 &
fi

if [ -f "$BASE/laptop_tester.py" ]; then
  exec python3 "$BASE/laptop_tester.py"
fi
SCRIPT

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "DRY-RUN: write $STARTUP_SCRIPT"
else
  printf '%s\n' "$STARTUP_CONTENT" > "$STARTUP_SCRIPT"
  chmod +x "$STARTUP_SCRIPT"
fi
log "Installed fast startup script: $STARTUP_SCRIPT"

# 3) Optional service trimming for test-image use case.
# Puppy variants differ a lot, so only touch files that exist.
declare -a OPTIONAL_INIT_SCRIPTS=(
  "$ROOTFS/etc/init.d/cups"
  "$ROOTFS/etc/init.d/bluetooth"
  "$ROOTFS/etc/init.d/samba"
  "$ROOTFS/etc/init.d/avahi-daemon"
)

if [[ "$AGGRESSIVE" -eq 1 ]]; then
  for svc in "${OPTIONAL_INIT_SCRIPTS[@]}"; do
    if [[ -f "$svc" && -x "$svc" ]]; then
      backup_file "$svc"
      run "chmod -x '$svc'"
      log "Disabled optional boot service: ${svc#$ROOTFS}"
    fi
  done
fi

# 4) Pre-compile Python files for faster first launch after boot.
if command -v python3 >/dev/null 2>&1; then
  COMPILE_TARGETS=(
    "$ROOTFS/root/laptoptester"
    "$ROOTFS/mnt/home/laptoptester"
  )

  for target in "${COMPILE_TARGETS[@]}"; do
    if [[ -d "$target" ]]; then
      run "python3 -m compileall -q '$target'"
      log "Compiled Python bytecode under: ${target#$ROOTFS}"
    fi
  done
fi

log "Done. Reimage with Clonezilla after validation boot test."
